config/routes.rb
class SubdomainConstraint
  def self.matches?(request)
    subdomains = %w{ www admin }
    request.subdomain.present? && !subdomains.include?(request.subdomain)
  end
end


Rails.application.routes.draw do

  # Devise authetication routes
  devise_for :users, controllers: { registrations: "registrations", sessions: "sessions" }

  # Routes for tenant subdomains
  constraints SubdomainConstraint do
    
    # subdomain admin area
    namespace :admin do
      get "/" => "dashboard#index"
      resources :pages # /admin/pages/ instead of /pages/
      get     "themes"        =>   "themes#index"
      post    "themes"        =>   "themes#update"
      get     "settings"      =>   "settings#index"
      post    "settings"      =>   "settings#update"
      get     "pricing"       =>   "subscriptions#pricing"
      get     "checkout"      =>   "subscriptions#checkout"
      post    "subscribe"     =>   "subscriptions#subscribe"
      post    "update-card"   =>   "subscriptions#update_card"
      delete  "unsubscribe"   =>   "subscriptions#unsubscribe"
    end

    # subdomain front-end area
    get '/' => 'pages#index', :constraints => SubdomainConstraint # subdomain root
    get '/:slug' => 'pages#show' # subdomain pages

  end

  # Routes for TLD (marketing site)
  root "home#index"

  # Stripe webhooks
  mount StripeEvent::Engine, at: '/stripe/webhooks' # provide a custom path

end

app/views/admin/pages/_form.html.erb
<%= form_for [ "admin" , @page] do |f| %>
  <% if @page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@page.errors.count, "error") %> prohibited this page from being saved:</h2>

      <ul>
      <% @page.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :slug %><br>
    <%= f.text_field :slug %>
  </div>
  <div class="field">
    <%= f.label :visibility %><br>
    <%= f.text_field :visibility %>
  </div>
  <div class="field">
    <%= f.label :menu_label %><br>
    <%= f.text_field :menu_label %>
  </div>
  <div class="field">
    <%= f.label :redirect_url %><br>
    <%= f.text_field :redirect_url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/pages/edit.html.erb
<h1>Editing Page</h1>

<%= render 'form' %>

<%= link_to 'Show', admin_page_path(@page) %> |
<%= link_to 'Back', admin_pages_path %>

app/views/admin/pages/index.html.erb
<p id="notice"><%= notice %></p>
&larr;<%= link_to('Back to Dashboard', admin_path) %>

<h1>Listing Pages</h1>
<p><%= page_usage_notice %></p>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th>Slug</th>
      <th>Visibility</th>
      <th>Menu label</th>
      <th>Redirect url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pages.each do |page| %>
      <tr>
        <td><%= page.title %></td>
        <td><%= page.body %></td>
        <td><%= page.slug %></td>
        <td><%= page.visibility %></td>
        <td><%= page.menu_label %></td>
        <td><%= page.redirect_url %></td>
        <td><%= link_to 'Show', admin_page_path(page) %></td>
        <td><%= link_to 'Edit', edit_admin_page_path(page) %></td>
        <td><%= link_to 'Destroy', admin_page_path(page), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>


<% if can? :create, :pages %>
  <%= link_to 'New Page', new_admin_page_path %>
<% end %>

app/views/admin/pages/new.html.erb
<h1>New Page</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_pages_path %>

app/views/admin/pages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @page.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @page.body %>
</p>

<p>
  <strong>Slug:</strong>
  <%= @page.slug %>
</p>

<p>
  <strong>Visibility:</strong>
  <%= @page.visibility %>
</p>

<p>
  <strong>Menu label:</strong>
  <%= @page.menu_label %>
</p>

<p>
  <strong>Redirect url:</strong>
  <%= @page.redirect_url %>
</p>

<%= link_to 'Edit', edit_admin_page_path(@page) %> |
<%= link_to 'Back', admin_pages_path %>