config/routes.rb
class SubdomainConstraint
  def self.matches?(request)
    subdomains = %w{ www admin }
    request.subdomain.present? && !subdomains.include?(request.subdomain)
  end
end


Rails.application.routes.draw do

  # Devise authetication routes
  devise_for :users, controllers: { registrations: "registrations", sessions: "sessions" }

  # Routes for tenant subdomains
  constraints SubdomainConstraint do
    
    # subdomain admin area
    namespace :admin do
      get "/" => "dashboard#index"
      resources :pages # /admin/pages/ instead of /pages/
      get     "themes"        =>   "themes#index"
      post    "themes"        =>   "themes#update"
      get     "settings"      =>   "settings#index"
      post    "settings"      =>   "settings#update"
      get     "pricing"       =>   "subscriptions#pricing"
      get     "checkout"      =>   "subscriptions#checkout"
      post    "subscribe"     =>   "subscriptions#subscribe"
      post    "update-card"   =>   "subscriptions#update_card"
      delete  "unsubscribe"   =>   "subscriptions#unsubscribe"
    end

    # subdomain front-end area
    get '/' => 'pages#index', :constraints => SubdomainConstraint # subdomain root
    get '/:slug' => 'pages#show' # subdomain pages

  end

  # Routes for TLD (marketing site)
  root "home#index"

  # Stripe webhooks
  mount StripeEvent::Engine, at: '/stripe/webhooks' # provide a custom path

end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < AdminController
  def index
  end
end

app/helpers/admin/dashboard_helper.rb
module Admin::DashboardHelper
end

app/views/admin/dashboard/index.html.erb
<h1>Welcome! <%= current_user.name %></h1>
<% if current_user_subscribed? %>
  <p>Your current plan is "<em><%= current_user.subscription_plan.capitalize %></em>" and your account is active untill <em><%= distance_of_time_in_words(Time.now, current_user.subscription_active_untill) %></em>.</p>
<% else %>
  <p>Hello! you are currently on 10-days free trial!</p>
<% end %>

<ul>
	<li><%= link_to('Pages', admin_pages_path) %></li>
	<li><%= link_to('Themes', admin_themes_path) %></li>
	<li><%= link_to('Settings', admin_settings_path) %></li>
	<li><%= link_to('Subscription', admin_pricing_path) %></li>
</ul>