config/routes.rb
class SubdomainConstraint
  def self.matches?(request)
    subdomains = %w{ www admin }
    request.subdomain.present? && !subdomains.include?(request.subdomain)
  end
end


Rails.application.routes.draw do

  # Devise authetication routes
  devise_for :users, controllers: { registrations: "registrations", sessions: "sessions" }

  # Routes for tenant subdomains
  constraints SubdomainConstraint do
    
    # subdomain admin area
    namespace :admin do
      get "/" => "dashboard#index"
      resources :pages # /admin/pages/ instead of /pages/
      get     "themes"        =>   "themes#index"
      post    "themes"        =>   "themes#update"
      get     "settings"      =>   "settings#index"
      post    "settings"      =>   "settings#update"
      get     "pricing"       =>   "subscriptions#pricing"
      get     "checkout"      =>   "subscriptions#checkout"
      post    "subscribe"     =>   "subscriptions#subscribe"
      post    "update-card"   =>   "subscriptions#update_card"
      delete  "unsubscribe"   =>   "subscriptions#unsubscribe"
    end

    # subdomain front-end area
    get '/' => 'pages#index', :constraints => SubdomainConstraint # subdomain root
    get '/:slug' => 'pages#show' # subdomain pages

  end

  # Routes for TLD (marketing site)
  root "home#index"

  # Stripe webhooks
  mount StripeEvent::Engine, at: '/stripe/webhooks' # provide a custom path

end

app/models/setting.rb
class Setting < ActiveRecord::Base
end

app/controllers/admin/settings_controller.rb
class Admin::SettingsController < AdminController

  def index
     @settings = {}
     pairs = Setting.pluck(:key, :value)
     pairs.each { |key, value| @settings[key] = value }
     @settings
  end

  def update
  	setting_params.each do |key, value|
  	  if Setting.where(key: key).present?
  		  Setting.where(key: key).first.update_attribute :value, value
  		else
  		  Setting.create(key: key, value: value)
  		end
  	end

  	Rails.application.reload_routes!
  	redirect_to admin_settings_path(@setting), notice: "Settings saved."
  end

  private

  def setting_params
  	params.require(:settings).permit(:homepage, :site_title, :site_desc, :site_url, :current_theme)
  end
  
end

app/helpers/admin/settings_helper.rb
module Admin::SettingsHelper

	def homepage_options
		grouped_options_for_select({
			"Pages" => Page.all.map { |page| [ page.title, url_for_page(page) ] }
		}, Setting.where(key: "homepage").first.value)
	end

end

app/views/admin/settings/index.html.erb
&larr;<%= link_to('Back to Dashboard', admin_path) %>

<h2>General</h2>

<%= form_tag admin_settings_path, method: "post" do %>

	<p>
		<label>Homepage:</label>
		<% # select_tag "settings[homepage]", homepage_options, class: "form-control" %>
	</p>

	<p>
		<label>Site Title:</label>
		<%= text_field_tag "settings[site_title]", @settings["site_title"] %>
	</p>
	
	<p>
		<label>Site Description:</label>
		<%= text_area_tag "settings[site_desc]", @settings["site_desc"] %>
	</p>
	
	<p>
		<label>Site URL:</label>
		<%= text_field_tag "settings[site_url]", @settings["site_url"] %>
	</p>

	<p>
		<label>Theme:</label>
		<%= text_field_tag "settings[current_theme]", @settings["current_theme"] %>
	</p>

	<p>
		<%= submit_tag "Save settings", class: "btn btn-primary" %>
	</p>

<% end %>

<% if current_user_subscribed? %>

	<hr>

	<h2>Update Card</h2>

	<p>Your current card on file is:</p>
	<div><%= current_user.card_brand %> **** **** **** <%= current_user.card_last_digits %></div>
	<div>Expires <%= current_user.card_exp_month %> / <%= current_user.card_exp_year %></div>
	<br>

	<%= form_tag admin_update_card_path, id: "payment-form" do %>

	  <span class="payment-errors"></span>

	  <div class="form-row">
	    <label>
	      <span>Card Number</span>
	      <input type="text" size="20" data-stripe="number">
	    </label>
	  </div>

	  <div class="form-row">
	    <label>
	      <span>Expiration (MM/YY)</span>
	      <input type="text" size="2" data-stripe="exp_month">
	    </label>
	    <span> / </span>
	    <input type="text" size="2" data-stripe="exp_year">
	  </div>

	  <div class="form-row">
	    <label>
	      <span>CVC</span>
	      <input type="text" size="4" data-stripe="cvc">
	    </label>
	  </div>

	  <%= hidden_field_tag "plan", params["plan"] %>

	  <input type="submit" class="submit" value="Update Card">

	<% end %>

	<hr>

     <h2>Unsubscribe</h2>
	<p>Unhappy? <%= button_to "Cancel my subscription", admin_unsubscribe_path, data: { confirm: "Are you sure?" }, method: :delete %></p>
<% end %>