config/routes.rb
class SubdomainConstraint
  def self.matches?(request)
    subdomains = %w{ www admin }
    request.subdomain.present? && !subdomains.include?(request.subdomain)
  end
end


Rails.application.routes.draw do

  # Devise authetication routes
  devise_for :users, controllers: { registrations: "registrations", sessions: "sessions" }

  # Routes for tenant subdomains
  constraints SubdomainConstraint do
    
    # subdomain admin area
    namespace :admin do
      get "/" => "dashboard#index"
      resources :pages # /admin/pages/ instead of /pages/
      get     "themes"        =>   "themes#index"
      post    "themes"        =>   "themes#update"
      get     "settings"      =>   "settings#index"
      post    "settings"      =>   "settings#update"
      get     "pricing"       =>   "subscriptions#pricing"
      get     "checkout"      =>   "subscriptions#checkout"
      post    "subscribe"     =>   "subscriptions#subscribe"
      post    "update-card"   =>   "subscriptions#update_card"
      delete  "unsubscribe"   =>   "subscriptions#unsubscribe"
    end

    # subdomain front-end area
    get '/' => 'pages#index', :constraints => SubdomainConstraint # subdomain root
    get '/:slug' => 'pages#show' # subdomain pages

  end

  # Routes for TLD (marketing site)
  root "home#index"

  # Stripe webhooks
  mount StripeEvent::Engine, at: '/stripe/webhooks' # provide a custom path

end

app/controllers/admin/subscriptions_controller.rb
class Admin::SubscriptionsController < AdminController
  
  # VIEW: Pricing Table
  def pricing
  end

  # VIEW: Payment Form
  def checkout
  end

  # PROCESS: Create a new subscriber
  def subscribe

  	# 1: Create/Retrive customer object from stripe server
    if current_user.stripe_customer_id?
      customer = Stripe::Customer.retrieve(current_user.stripe_customer_id)
    else
      customer = Stripe::Customer.create(email: current_user.email)
    end

    # 2: Create/Retrive subscription object on stripe server (based on above customer)
    if current_user.stripe_subscription_id?
      subscription = customer.subscriptions.retrieve(current_user.stripe_subscription_id)
      subscription.source = params[:stripeToken] if params[:stripeToken]
      subscription.plan = params[:plan]
      subscription.save
    else
      subscription = customer.subscriptions.create(
                        source: params[:stripeToken],
                        plan: params[:plan]
                      )
    end

    
    # 3: Save Customer & Subscription attrs. to our DB
    options = {
      stripe_customer_id: customer[:id],
      stripe_subscription_id: subscription[:id],
      subscription_plan: subscription[:plan][:id],
      subscription_active_untill: Time.at(subscription[:current_period_end]).utc
    }

    # Only update the card on file if we're adding a new one
    options.merge!(
      card_brand: params[:card_brand],
      card_last_digits: params[:card_last_digits],
      card_exp_month: params[:card_exp_month],
      card_exp_year: params[:card_exp_year]
    ) if params[:card_last_digits]

    # Update user values in our DB
    current_user.update(options)

    # Redirect to user's dashboard
		redirect_to admin_path, flash: {notice: "Subscribed to #{params[:plan]} plan sucessfully"}  	

  end

  # PROCESS: Update card in stripe server and user table
  def update_card
    customer = Stripe::Customer.retrieve(current_user.stripe_customer_id)
    subscription = customer.subscriptions.retrieve(current_user.stripe_subscription_id)
    subscription.source = params[:stripeToken]
    subscription.save

    current_user.update(
      card_brand: params[:card_brand],
      card_last_digits: params[:card_last_digits],
      card_exp_month: params[:card_exp_month],
      card_exp_year: params[:card_exp_year]
    )

    redirect_to admin_settings_path, notice: "Successfully updated your card"
  end

  # PROCESS: Cancel user's subscription
  def unsubscribe
    customer = Stripe::Customer.retrieve(current_user.stripe_customer_id)
    customer.subscriptions.retrieve(current_user.stripe_subscription_id).delete
    current_user.update(stripe_subscription_id: nil, subscription_plan: nil, subscription_active_untill: nil)

    redirect_to admin_settings_path, notice: "Your subscription has been canceled."
  end

end

app/helpers/admin/subscriptions_helper.rb
module Admin::SubscriptionsHelper
end

app/views/admin/subscriptions/checkout.html.erb
&larr;<%= link_to('Back to Dashboard', admin_path) %>


<h1>Checkout</h1>

<% if current_user.stripe_subscription_id? %>
  <p>You are changing your plan from "<%= current_user.subscription_plan.capitalize %>" to "<%= params[:plan].capitalize %>"</p>
<% else %>
  <p>You will be subscribed for the "<%= params[:plan].capitalize %>" plan.</p>
<% end %>


<%= form_tag admin_subscribe_path, id: "payment-form" do %>

  <!-- OLD SUBSCRIBER -->
  <% if current_user.card_last_digits? %>
    <div class="card-on-file">
      <p>Your current card on file is:</p>
      <div><%= current_user.card_brand %> **** **** **** <%= current_user.card_last_digits %></div>
      <div>Expires <%= current_user.card_exp_month %> / <%= current_user.card_exp_year %></div>
      <p><%= link_to "Use a different card", "#", class: "use-different-card" %></p>
    </div>
  <% end %>

  <!-- NEW SUBSCRIBER -->
  <div class="card-fields <%= card_fields_class %>">

    <span class="payment-errors"></span>

    <div class="form-row">
      <label>
        <span>Card Number</span>
        <input value="4242424242424242" type="text" size="20" data-stripe="number">
      </label>
    </div>

    <div class="form-row">
      <label>
        <span>Expiration (MM/YY)</span>
        <input value="4" type="text" size="2" data-stripe="exp_month">
      </label>
      <span> / </span>
      <input value="18" type="text" size="2" data-stripe="exp_year">
    </div>

    <div class="form-row">
      <label>
        <span>CVC</span>
        <input value="217" type="text" size="4" data-stripe="cvc">
      </label>
    </div>

    <%= hidden_field_tag "plan", params["plan"] %>

  </div>

  <input type="submit" class="submit" value="Submit Payment">

<% end %>

app/views/admin/subscriptions/pricing.html.erb
&larr;<%= link_to('Back to Dashboard', admin_path) %>
<br><br>

<h1>Our Plans</h1>
<br>

<h3>Basic</h3>
<p>Priced @ $6.00 per month (billed monthly)</p>
<p>Priced @ $8.00 per month (billed annually)</p>

<% if current_user.subscription_plan != "basic" %>
	<%= link_to('Select Plan', admin_checkout_path(:plan => "basic")) %>
<% else %>
	<em>(Currently Active Plan)</em>
<% end %>


<br><br>

<h3>Professional</h3>
<p>Priced @ $8.00 per month (billed monthly)</p>
<p>Priced @ $10.00 per month (billed annually)</p>

<% if current_user.subscription_plan != "professional" %>
	<%= link_to('Select Plan', admin_checkout_path(:plan => "professional")) %>
<% else %>
	<em>(Currently Active Plan)</em>
<% end %>

<br><br>

<h3>Agency</h3>
<p>Priced @ $19.00 per month (billed monthly)</p>
<p>Priced @ $25.00 per month (billed annually)</p>

<% if current_user.subscription_plan != "agency" %>
	<%= link_to('Select Plan', admin_checkout_path(:plan => "agency")) %>
<% else %>
	<em>(Currently Active Plan)</em>
<% end %>